name: Build and push docker image on new tag

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: 'lmerza'
  DOCKERHUB_REPO: ${{ env.DOCKERHUB_REPO }}
        
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Determine TAG_NAME from latest tag
      run: |
        echo "TAG_NAME=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
  
    - name: Prepare docker tags
      run: |
        DOCKER_TAGS="${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPO }}:${TAG_NAME}"
        DOCKER_TAGS="$DOCKER_TAGS,${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPO }}:latest"
        echo "DOCKER_TAGS=$DOCKER_TAGS" >> $GITHUB_ENV

    - name: Print tag env
      run: |
        echo $DOCKER_TAGS
        echo $TAG_NAME

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ env.DOCKER_TAGS }}
        build-args: TAG_NAME=${{ env.TAG_NAME }}
    
    # - name: Create Release
    #   id: create_release
    #   uses: ncipollo/release-action@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     draft: false
    #     prerelease: false
    #     generateReleaseNotes: true